import {
  createPrivateKey,
  generateKeyPairSync,
  type KeyObject,
} from 'node:crypto';
import {
  closeSync,
  constants,
  fchmodSync,
  lstatSync,
  mkdirSync,
  openSync,
  readFileSync,
  writeFileSync,
} from 'node:fs';
import { homedir } from 'node:os';
import { dirname, join } from 'node:path';
import { type HolderPublicJwk, parseHolderPublicJwk } from '@stripe/link-sdk';

export const DEFAULT_HOLDER_KEY_PATH = join(
  homedir(),
  '.link',
  'holder-key.jwk',
);

export interface HolderKey {
  privateKey: KeyObject;
  publicJwk: HolderPublicJwk;
  /** True when the key was generated by this call rather than read from disk. */
  created: boolean;
}

interface StoredHolderKey {
  private_jwk: Record<string, unknown>;
}

function readHolderKeyFile(path: string): string {
  if (lstatSync(path).isSymbolicLink()) {
    throw new Error('holder key path is a symbolic link');
  }

  const noFollowFlag = constants.O_NOFOLLOW ?? 0;
  const descriptor = openSync(path, constants.O_RDONLY | noFollowFlag);
  try {
    return readFileSync(descriptor, 'utf8');
  } finally {
    closeSync(descriptor);
  }
}

function toPublicJwk(privateKey: KeyObject): HolderPublicJwk {
  const jwk = privateKey.export({ format: 'jwk' }) as Record<string, string>;

  // Export only the public members so the private scalar never leaves the
  // local key file.
  return parseHolderPublicJwk(jwk);
}

function generateHolderKey(): KeyObject {
  return generateKeyPairSync('ed25519').privateKey;
}

/**
 * Loads the holder key from `path`, generating and persisting one if the file
 * does not exist yet. The credential is bound to this key, so it must be
 * reusable across runs to be presentable later: the file is written with 0600
 * permissions and holds the private JWK.
 */
export function loadOrCreateHolderKey(path: string): HolderKey {
  let stored: StoredHolderKey | undefined;
  try {
    stored = JSON.parse(readHolderKeyFile(path)) as StoredHolderKey;
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== 'ENOENT') {
      throw new Error(
        `Failed to read holder key at ${path}: ${(error as Error).message}`,
      );
    }
  }

  if (stored) {
    const privateKey = createPrivateKey({
      key: stored.private_jwk as never,
      format: 'jwk',
    });
    return {
      privateKey,
      publicJwk: toPublicJwk(privateKey),
      created: false,
    };
  }

  const privateKey = generateHolderKey();
  const payload: StoredHolderKey = {
    private_jwk: privateKey.export({ format: 'jwk' }) as Record<
      string,
      unknown
    >,
  };

  mkdirSync(dirname(path), { recursive: true, mode: 0o700 });
  const noFollowFlag = constants.O_NOFOLLOW ?? 0;
  let descriptor: number | undefined;
  try {
    descriptor = openSync(
      path,
      constants.O_CREAT | constants.O_EXCL | constants.O_WRONLY | noFollowFlag,
      0o600,
    );
    writeFileSync(descriptor, `${JSON.stringify(payload, null, 2)}\n`);
    fchmodSync(descriptor, 0o600);
  } catch (error) {
    throw new Error(
      `Failed to write holder key at ${path}: ${(error as Error).message}`,
      { cause: error },
    );
  } finally {
    if (descriptor !== undefined) {
      closeSync(descriptor);
    }
  }

  return {
    privateKey,
    publicJwk: toPublicJwk(privateKey),
    created: true,
  };
}

/**
 * Loads an existing holder key. Does not generate a replacement: a missing
 * file is an error so an existing credential cannot be paired with a new key.
 */
export function loadHolderKey(path: string): HolderKey {
  let stored: StoredHolderKey;
  try {
    stored = JSON.parse(readHolderKeyFile(path)) as StoredHolderKey;
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') {
      throw new Error(
        `Holder key not found at ${path}. Issue a new credential to create it.`,
      );
    }
    throw new Error(
      `Failed to read holder key at ${path}: ${(error as Error).message}`,
    );
  }

  const privateKey = createPrivateKey({
    key: stored.private_jwk as never,
    format: 'jwk',
  });
  return {
    privateKey,
    publicJwk: toPublicJwk(privateKey),
    created: false,
  };
}
