import { spawnSync } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';

const SKILLS_REPOSITORY = 'stripe/link-cli';

// Prior art: Shopify's ucp-cli uses the same pre-dispatch interception point to
// replace Incur's generated skill sync with curated behavior:
// https://github.com/Shopify/ucp-cli/blob/main/src/cli/skills-sync.ts
export function isSkillsAddInvocation(argv: readonly string[]): boolean {
  return (
    (argv[0] === 'skills' || argv[0] === 'skill') &&
    argv[1] === 'add' &&
    !argv.includes('--help') &&
    !argv.includes('-h')
  );
}

type InstallerRunner = (
  command: string,
  args: readonly string[],
  env: NodeJS.ProcessEnv,
) => number;
type LegacySkillsCleanup = () => void;

export function installAuthoredSkills(
  argv: readonly string[],
  run: InstallerRunner = runInstaller,
  cleanupLegacySkills: LegacySkillsCleanup = removeLegacyIncurSkills,
): number {
  const args = ['--yes', 'skills', 'add', SKILLS_REPOSITORY];
  if (!argv.includes('--no-global')) args.push('-g');
  args.push('-y');
  const status = run('npx', args, { ...process.env, GH_HOST: 'github.com' });
  if (status === 0) cleanupLegacySkills();
  return status;
}

/**
 * Removes skills generated by Incur's former `skills add` implementation and
 * its staleness metadata. Authored skills such as `link-cli` are not matched.
 */
export function removeLegacyIncurSkills(
  options: {
    cwd?: string;
    dataHome?: string;
    homeDir?: string;
  } = {},
): void {
  const homeDir = options.homeDir ?? os.homedir();
  const dataHome =
    options.dataHome ??
    process.env.XDG_DATA_HOME ??
    path.join(homeDir, '.local', 'share');
  const metadataPath = path.join(dataHome, 'incur', 'link-cli.json');

  let metadata: unknown;
  try {
    metadata = JSON.parse(fs.readFileSync(metadataPath, 'utf8'));
  } catch {
    return;
  }

  if (!isRecord(metadata) || !Array.isArray(metadata.skills)) return;
  const legacySkillNames = new Set(
    metadata.skills.filter(
      (skill): skill is string =>
        typeof skill === 'string' && skill.startsWith('link-cli-'),
    ),
  );
  if (legacySkillNames.size === 0) return;

  const recordedPaths = Array.isArray(metadata.paths)
    ? metadata.paths.filter((skillPath): skillPath is string =>
        isRecordedLegacySkillPath(skillPath, legacySkillNames),
      )
    : [];
  const legacySkillPaths =
    recordedPaths.length > 0
      ? recordedPaths
      : [...legacySkillNames].flatMap((skill) => [
          path.join(homeDir, '.agents', 'skills', skill),
          path.join(options.cwd ?? process.cwd(), '.agents', 'skills', skill),
        ]);

  for (const skillPath of new Set(legacySkillPaths)) {
    fs.rmSync(skillPath, { force: true, recursive: true });
  }
  fs.rmSync(metadataPath, { force: true });
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null;
}

function isRecordedLegacySkillPath(
  skillPath: string,
  legacySkillNames: ReadonlySet<string>,
): boolean {
  const resolvedPath = path.resolve(skillPath);
  return (
    path.isAbsolute(skillPath) &&
    legacySkillNames.has(path.basename(resolvedPath)) &&
    path.basename(path.dirname(resolvedPath)) === 'skills' &&
    path.basename(path.dirname(path.dirname(resolvedPath))) === '.agents'
  );
}

function runInstaller(
  command: string,
  args: readonly string[],
  env: NodeJS.ProcessEnv,
): number {
  const result = spawnSync(command, [...args], { env, stdio: 'inherit' });
  if (result.error) {
    process.stderr.write(
      `Failed to install Link CLI skills: ${result.error.message}\n`,
    );
    return 1;
  }
  return result.status ?? 1;
}
