import { spawnSync } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { SyncSkills } from 'incur';

declare const __AUTHORED_SKILLS__: Readonly<Record<string, string>>;

const SKILLS_REPOSITORY = 'stripe/link-cli';

// Prior art: Shopify's ucp-cli uses the same pre-dispatch interception point to
// replace Incur's generated skill sync with curated behavior:
// https://github.com/Shopify/ucp-cli/blob/main/src/cli/skills-sync.ts
export function isSkillsAddInvocation(argv: readonly string[]): boolean {
  const filtered = withoutIncurGlobalFlags(argv);
  return (
    (filtered[0] === 'skills' || filtered[0] === 'skill') &&
    filtered[1] === 'add' &&
    !argv.includes('--help') &&
    !argv.includes('-h')
  );
}

function withoutIncurGlobalFlags(argv: readonly string[]): string[] {
  const filtered: string[] = [];
  const flagsWithValues = new Set([
    '--filter-output',
    '--format',
    '--token-limit',
    '--token-offset',
  ]);
  const flagsWithoutValues = new Set([
    '--full-output',
    '--incur-update-check',
    '--json',
    '--llms',
    '--llms-full',
    '--mcp',
    '--schema',
    '--token-count',
    '--update',
  ]);

  for (let index = 0; index < argv.length; index++) {
    const token = argv[index];
    if (token === undefined) continue;
    if (flagsWithValues.has(token) && argv[index + 1] !== undefined) {
      index++;
      continue;
    }
    if (flagsWithoutValues.has(token)) continue;
    if (
      token === '--version' &&
      (argv[index + 1] === undefined || argv[index + 1]?.startsWith('-'))
    ) {
      continue;
    }
    filtered.push(token);
  }
  return filtered;
}

type InstallerRunner = (
  command: string,
  args: readonly string[],
  env: NodeJS.ProcessEnv,
) => number;
type LegacySkillsCleanup = () => void;

export function installAuthoredSkills(
  argv: readonly string[],
  run: InstallerRunner = runInstaller,
  cleanupLegacySkills: LegacySkillsCleanup = removeLegacyIncurSkills,
): number {
  const args = ['--yes', 'skills', 'add', SKILLS_REPOSITORY];
  if (!argv.includes('--no-global')) args.push('-g');
  args.push('-y');
  const status = run('npx', args, { ...process.env, GH_HOST: 'github.com' });
  if (status === 0) cleanupLegacySkills();
  return status;
}

/** Installs the embedded authored skills without requiring Node or npm. */
export async function installAuthoredSkillsNatively(
  argv: readonly string[],
  options: {
    authoredSkills?: Readonly<Record<string, string>>;
    cwd?: string;
    removeMetadata?: () => void;
    syncSkills?: typeof SyncSkills.sync;
  } = {},
): Promise<number> {
  const global = !argv.includes('--no-global');
  const cwd = options.cwd ?? process.cwd();
  const stagingParent = global ? os.tmpdir() : cwd;
  const stagingDirectory = fs.mkdtempSync(
    path.join(stagingParent, 'link-cli-skills-'),
  );
  const authoredSkills = options.authoredSkills ?? __AUTHORED_SKILLS__;

  try {
    for (const [relativePath, content] of Object.entries(authoredSkills)) {
      const target = path.resolve(stagingDirectory, relativePath);
      if (!target.startsWith(`${stagingDirectory}${path.sep}`)) {
        throw new Error(`Invalid embedded skill path: ${relativePath}`);
      }
      fs.mkdirSync(path.dirname(target), { recursive: true });
      fs.writeFileSync(target, content);
    }

    const syncCwd = global ? stagingDirectory : cwd;
    const includeRoot = global ? '.' : path.relative(cwd, stagingDirectory);
    await (options.syncSkills ?? SyncSkills.sync)(
      'link-cli-authored',
      new Map(),
      {
        cwd: syncCwd,
        global,
        include: [path.join(includeRoot, '*')],
      },
    );
    (options.removeMetadata ?? finalizeNativeInstall)();
    return 0;
  } catch (error) {
    process.stderr.write(
      `Failed to install Link CLI skills: ${error instanceof Error ? error.message : String(error)}\n`,
    );
    return 1;
  } finally {
    fs.rmSync(stagingDirectory, { force: true, recursive: true });
  }
}

/**
 * Removes skills generated by Incur's former `skills add` implementation and
 * its staleness metadata. Authored skills such as `link-cli` are not matched.
 */
export function removeLegacyIncurSkills(
  options: {
    cwd?: string;
    dataHome?: string;
    homeDir?: string;
  } = {},
): void {
  const homeDir = options.homeDir ?? os.homedir();
  const dataHome =
    options.dataHome ??
    process.env.XDG_DATA_HOME ??
    path.join(homeDir, '.local', 'share');
  const metadataPath = incurMetadataPath(dataHome);

  let metadata: unknown;
  try {
    metadata = JSON.parse(fs.readFileSync(metadataPath, 'utf8'));
  } catch {
    return;
  }

  if (!isRecord(metadata) || !Array.isArray(metadata.skills)) return;
  const legacySkillNames = new Set(
    metadata.skills.filter(
      (skill): skill is string =>
        typeof skill === 'string' && skill.startsWith('link-cli-'),
    ),
  );
  if (legacySkillNames.size === 0) return;

  const recordedPaths = Array.isArray(metadata.paths)
    ? metadata.paths.filter((skillPath): skillPath is string =>
        isRecordedLegacySkillPath(skillPath, legacySkillNames),
      )
    : [];
  const legacySkillPaths =
    recordedPaths.length > 0
      ? recordedPaths
      : [...legacySkillNames].flatMap((skill) => [
          path.join(homeDir, '.agents', 'skills', skill),
          path.join(options.cwd ?? process.cwd(), '.agents', 'skills', skill),
        ]);

  for (const skillPath of new Set(legacySkillPaths)) {
    fs.rmSync(skillPath, { force: true, recursive: true });
  }
  fs.rmSync(metadataPath, { force: true });
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null;
}

function isRecordedLegacySkillPath(
  skillPath: string,
  legacySkillNames: ReadonlySet<string>,
): boolean {
  const resolvedPath = path.resolve(skillPath);
  return (
    path.isAbsolute(skillPath) &&
    legacySkillNames.has(path.basename(resolvedPath)) &&
    path.basename(path.dirname(resolvedPath)) === 'skills'
  );
}

function incurMetadataPath(dataHome?: string, name = 'link-cli'): string {
  const resolvedDataHome =
    dataHome ??
    process.env.XDG_DATA_HOME ??
    path.join(os.homedir(), '.local', 'share');
  return path.join(resolvedDataHome, 'incur', `${name}.json`);
}

function finalizeNativeInstall(): void {
  removeLegacyIncurSkills();
  fs.rmSync(incurMetadataPath(undefined, 'link-cli-authored'), { force: true });
}

function runInstaller(
  command: string,
  args: readonly string[],
  env: NodeJS.ProcessEnv,
): number {
  const result = spawnSync(command, [...args], { env, stdio: 'inherit' });
  if (result.error) {
    process.stderr.write(
      `Failed to install Link CLI skills: ${result.error.message}\n`,
    );
    return 1;
  }
  return result.status ?? 1;
}
